# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d48c030288d76023b2a4f97960d605a57363c54700aca9745e021df66557ca2e75629cc513c3d10ddb906e391dad5c4f0d6e3614891a7fef6e7e9f5cae8a620

test:
  secret_key_base: 2c6eebebf098cd2d1321407676f4ce5a9f14cfb1ad72ee04a7eb42772bb9d788e5ecc5feda44c50d12fc662742422767308666ec4524948e3d2591e1f207fed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
